name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.hehe}}
          heroku_app_name: "tailoring" #Must be unique in Heroku
          heroku_email: "2021847636@student.uitm.edu.my"
